version: '3'

services:
  web:
    image: php84-cli-hemascorecard
    build:
      context: .
      dockerfile_inline: |
        FROM php:8.4.5-cli
        RUN docker-php-ext-install mysqli && \
            docker-php-ext-enable mysqli && \
            pecl install xdebug && \
            docker-php-ext-enable xdebug
      tags:
        - php84-cli-hemascorecard
    command: php -S 0.0.0.0:8000 -t /hemaScorecard
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes: 
      - .:/hemaScorecard
    links:
      - db

  db:
    image: mysql:8.0.36
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./includes:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql